name: .NET Core PR

on: 
    pull_request:
        branches:
        - main
jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET 10
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '10.0.x'
        dotnet-quality: 'preview'
    - name: Build Library
      run: dotnet build --configuration Release ./AsyncPlinq/AsyncPlinq.csproj
